app.config(function($stateProvider,$urlRouterProvider){
  $urlRouterProvider.otherwise('/');
  $stateProvider.state('app.home',{
    url:'/home',
    templateUrl:'templates/home.html',
    controller:'ArticleController'
  }).
  state('app.articleOne',{
    url:'/article-one',
    templateUrl:'templates/article.html'
  }).
  state('app.readArticle',{
    url:'/readarticle?id',
    templateUrl:'templates/readarticle.html',
    controller:'ArticleController'
  }).
  state('app.newArticle',{
    url:'/new_article',
    templateUrl:'templates/newArticle.html',
    controller:'ArticleController'
  }).
  state('profile',{
    url:'/',
    templateUrl:'templates/profile.html'
  }).
  state('app',{
    url:'/app-home',
    templateUrl:'templates/app-home.html'
  });
});
